# -*- coding: utf-8 -*-
"""Zadania-06-11-2023

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZtKDGAH_Voh_9htvda3vOqgk_ahKi3X3

Zadanie 1
"""


def przywitaj(name, surname):
    wynik = f'Cześć {name} {surname}!'
    return wynik


name = "Kasia"
surname = "Wolna"
wynik_funkcji = przywitaj(name, surname)

print(wynik_funkcji)


""" Zadanie 2 """


def pomnoz(a, b):
    wynik = a * b

    return wynik


liczba1 = 2
liczba2 = 7

wynik_mnozenia = pomnoz(liczba1, liczba2)
print(wynik_mnozenia)

""" Zadanie 3 """


def czy_parzysta(liczba):
    if liczba % 2 == 0:
        return True
    else:
        return False


liczba = 2
wynik_funkcji = czy_parzysta(liczba)

if wynik_funkcji:
    print("Liczba parzysta")
else:
    print("Liczba nieparzysta")


""" Zadanie 4 """


def sprawdz_sume(a, b, c):
    suma = a + b
    if suma < c:
        return False
    else:
        return True


liczba1 = 2
liczba2 = 6
liczba3 = 9
wynik_funkcji = sprawdz_sume(liczba1, liczba2, liczba3)

print(wynik_funkcji)

""" Zadanie 5 """


def sprawdz_obecnosc_wartosci(lista, wartosc):
    if wartosc not in lista:
        return True
    else:
        return False


moja_lista = [1, 2, 3, 4, 5]
szukana_wartosc = 3

wynik_funkcji = sprawdz_obecnosc_wartosci(moja_lista, szukana_wartosc)

print(wynik_funkcji)


""" Zadanie 6 """


def przetworz_listy(lista1, lista2):

    polaczona_lista = lista1 + lista2
    unikalna_lista = list(set(polaczona_lista))
    lista_potegowana = [x ** 3 for x in unikalna_lista]
    return lista_potegowana


lista1 = [1, 2, 3, 4]
lista2 = [2, 4, 6, 8]

wynik_funkcji = przetworz_listy(lista1, lista2)


print(wynik_funkcji)
