# -*- coding: utf-8 -*-
"""Zadania-06-11-2023

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZtKDGAH_Voh_9htvda3vOqgk_ahKi3X3

Zadanie 1
"""

def przywitaj(name, surname):
    wynik = f'Cześć {name} {surname}!'
    return wynik

name = "Kasia"
surname = "Wolna"
wynik_funkcji = przywitaj(name, surname)
print(wynik_funkcji)

"""Zadanie 2"""

def pomnóż(a, b):
    wynik = a * b
    return wynik

liczba1 = 2
liczba2 = 7
wynik_mnożenia = pomnóż(liczba1, liczba2)
print(wynik_mnożenia)

"""Zadanie 3"""

def czy_parzysta(liczba):
    if liczba % 2 == 0:
        return True
    else:
        return False

liczba = 2
wynik_funkcji = czy_parzysta(liczba)

if wynik_funkcji:
    print("Liczba parzysta")
else:
    print("Liczba nieparzysta")

"""Zadanie 4"""

def sprawdź_sumę(a, b, c):
    suma = a + b
    if suma >= c:
        return True
    else:
        return False

liczba1 = 2
liczba2 = 6
liczba3 = 9
wynik_funkcji = sprawdź_sumę(liczba1, liczba2, liczba3)

print(wynik_funkcji)

"""Zadanie 5"""

def sprawdź_obecność_wartości(lista, wartość):
    if wartość in lista:
        return True
    else:
        return False

moja_lista = [1, 2, 3, 4, 5]
szukana_wartość = 3
wynik_funkcji = sprawdź_obecność_wartości(moja_lista, szukana_wartość)

print(wynik_funkcji)

"""Zadanie 6"""

def przetwórz_listy(lista1, lista2):
    połączona_lista = lista1 + lista2
    unikalna_lista = list(set(połączona_lista))
    lista_potęgowana = [x ** 3 for x in unikalna_lista]
    return lista_potęgowana

lista1 = [1, 2, 3, 4]
lista2 = [2, 4, 6, 8]
wynik_funkcji = przetwórz_listy(lista1, lista2)

print(wynik_funkcji)